### ISSUE TITLE
train dataset

### ISSUE THREAD

**Issue by zzinzziny** [hanish3464/WORD-pytorch#7]
Hi.
Can you please tell me roughly the details of train datasets of object detection and text detection? (i.e. kinds of data, number of data, data format....)

**Comment by hanish3464** [comment]
@ji-in0615 

I am sorry about the late reply. 

In the case of object detection, I used about 2000 images for training. 
In the case of text detection, the CRAFT model was used without training. 
What changed in text detection is only the code for post-processing.

I don't check github very often.
If you have any further questions, please contact the open chat room at https://open.kakao.com/o/gLePrL8e.
